### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aauss** [ecohealthalliance/EpiTator#39]
Hello!
Seeing EpiTator's work in GRITS is astonishing. It would really love to use it myself, but I have problems to expand my work past the provided code examples. The framework is large and I feel I won't be able to use it with all its possibilites without having a documentation. Do you have one that you are willing to share?
All the best,
Auss

**Comment by nathanathan** [comment]
We built a documentation website here: https://epitator.readthedocs.io/en/latest/index.html
It provides more information about the AnnoDoc/AnnoTier/AnnoSpan classes.
