### ISSUE TITLE
How can I contribute

### ISSUE THREAD

**Issue by aauss** [ecohealthalliance/EpiTator#45]
Hello!
I have been working with EpiTator for a while now, and I would love to contribute. Is there any guideline on how to contribute, or can I just make a pull request with my changes?
Looking forward to hear back from you,
Auss

**Comment by nathanathan** [comment]
Hi Aauss, Feel free to open pull requests. We don't have any established guidelines, but if you want to add new features they should have a few tests, and we would prefer to not add dependencies on additional libraries if it can be avoided. We would be hesitant to add new annotators to this repository, but if you put the annotators in a separate repo or pypi package we could add links to them. Bug fixes (or reports) and improvements to the documentation and tests are the most useful contributions for us.
Thanks,
-Nathan

**Comment by aauss** [comment]
Thank you.
